[package]
name = "needletail"
version = "0.3.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]
description = "FASTX parsing and k-mer methods"
keywords = ["FASTA", "FASTQ", "kmer", "bioinformatics"]
categories = ["science", "parsing"]
repository = "https://github.com/onecodex/needletail"
license = "MIT"
readme = "./README.md"
edition = "2018"

[features]
default = ["compression"]
compression = ["bzip2", "flate2", "xz2"]

[dependencies]
flate2 = { version="1.0.6", optional=true }
bzip2 = { version="0.3.3", optional=true }
xz2 = { version="0.1.6", optional=true }
memchr = "2.2.1"
safemem = "0.3.2"

[dev-dependencies]
criterion = "0.3"

# for benchmark comparisons
bio = "0.28"
seq_io = "0.3"

# for testing with the FormatSpecimens.jl repo
reqwest = "0.9"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"

[[bench]]
name = "benchmark"
harness = false
